# Generated by Django 5.1.2 on 2024-11-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Am_app', '0002_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Completed_project',
        ),
        migrations.DeleteModel(
            name='Detailed',
        ),
        migrations.DeleteModel(
            name='Dop',
        ),
        migrations.DeleteModel(
            name='Elevation',
        ),
        migrations.DeleteModel(
            name='Fabrication',
        ),
        migrations.DeleteModel(
            name='Freelancing',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='Joinventure',
        ),
        migrations.DeleteModel(
            name='Landscape',
        ),
        migrations.DeleteModel(
            name='Listofmachine',
        ),
        migrations.DeleteModel(
            name='Ongoing_project',
        ),
        migrations.DeleteModel(
            name='Paintcontract',
        ),
        migrations.DeleteModel(
            name='Renovation',
        ),
        migrations.DeleteModel(
            name='Residential',
        ),
        migrations.DeleteModel(
            name='Retro',
        ),
        migrations.DeleteModel(
            name='Service_image',
        ),
        migrations.DeleteModel(
            name='Struturaldesign',
        ),
        migrations.DeleteModel(
            name='Swimming',
        ),
    ]
